--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockMagicDev/UnlimitedSlots
build-by-default: true
branches:
- main
projects:
  UnlimitedSlot:
    icon: icon.png
    path: PocketMine-MP/
...
